### ISSUE TITLE
couldn't  initialize gonvml

### ISSUE THREAD

**Issue by quelle1** [mindprince/nvidia_gpu_prometheus_exporter#13]
system info: ubuntu 16.04
gpu: rtx 2080Ti
cuda: 10
nvidia-driver:410.48

when I create the nvidia-gpu-prometheus-exporter, the pod error, the message is "couldn't initialize gonvml: could not load NVML library Make sure NVML is in the shared library search path"

**Comment by quelle1** [comment]
I have solved this problem， because the /etc/docker/daemon.json is wrong

**Comment by gacalheiros** [comment]
What was wrong in your daemon.json? How did you fix it?
