### ISSUE TITLE
Official docker image?

### ISSUE THREAD

**Issue by hmeine** [mindprince/nvidia_gpu_prometheus_exporter#3]
Similar to @discordianfish in #1, I am interested in running this exporter via docker. Would it be possible to provide an "official" image, e.g. on the main Docker hub?

**Comment by hmeine** [comment]
I found https://hub.docker.com/r/fish/nvidia_gpu_prometheus_exporter/
Should we link to it from the README, then?
Update: I just realized that @discordianfish is maybe the person I should trust most about delivering an image – sorry about asking for an "official" account. (If anybody took a screenshot of my posting, that belongs to `/r/dontyouknowwhoiam/` ;-) )

**Comment by discordianfish** [comment]
Hi :)
Yeah, ideally we should include the Dockerfile here (See my PR #2). Doesn't make much sense to maintain a fork just to include a Dockerfile. For now though it's being used over here and kept up to date but that could change in the future.

**Comment by adampl** [comment]
The image mentioned above didn't work for me:
```
$ docker run -p 9445:9445 -v /usr/lib/nvidia-396:/nvlibs -e LD_LIBRARY_PATH=/nvlibs fish/nvidia_gpu_prometheus_exporter
2018/10/25 17:50:23 Couldn't initialize gonvml: could not load NVML library. Make sure NVML is in the shared library search path.
```
Is this correct? If not, please let me know.

However, in my PR #5 I've suggested another approach using Nvidia CUDA image to avoid exposing libraries, and it works OK.

In both cases I'm using the Nvidia Docker runtime.

**Comment by hmeine** [comment]
I have the same problem. I used `--entrypoint` to verify with `ldd` that the library is there and does not miss dependencies.  Probably, the image (based on "Debian GNU/Linux 9 (stretch)") is somehow incompatible with my host system (Ubuntu 18.04.1 LTS with NVIDIA driver version 390.87).
I agree that basing the container on a CUDA image would be more robust.

**Comment by rohitagarwal003** [comment]
Hi,

There's now a Dockerfile in the repo and instructions to use the exporter from inside a docker container: https://github.com/mindprince/nvidia_gpu_prometheus_exporter#running-inside-a-container.

I have pushed the docker image to https://hub.docker.com/r/mindprince/nvidia_gpu_prometheus_exporter/

There's nothing CUDA specific needed by the exporter, https://github.com/mindprince/nvidia_gpu_prometheus_exporter/commit/219f582c6fca23d200e8e3b5069ef9bc28451389 describes what is needed by nvidia-container-runtime to inject the NVML libraries in the container.
