### ISSUE TITLE
 FanSpeed() error: nvml: Not Supported

### ISSUE THREAD

**Issue by ZhengRongTan** [mindprince/nvidia_gpu_prometheus_exporter#6]
![image](https://user-images.githubusercontent.com/8637734/48756836-a679f600-ecd5-11e8-8ae9-f7678ca866d0.png)

**Comment by rohitagarwal003** [comment]
This error is because your GPU card doesn't support this method. You can ignore this, the exporter should work even with this error.

**Comment by kernelpanic700** [comment]
> 
> 
> This error is because your GPU card doesn't support this method. You can ignore this, the exporter should work even with this error.

How to disable fan speed metric in exporter parameters ?
