### ISSUE TITLE
Heads-up: nvidia_gpu_prometheus_exporter is now packaged in FreeBSD

### ISSUE THREAD

**Issue by 0mp** [mindprince/nvidia_gpu_prometheus_exporter#8]
Just for your information, nvidia_gpu_prometheus_exporter has been added to the FreeBSD Ports Collection recently. It is now possible to download it as a package on FreeBSD with its package manager `pkg`.

Cheers!

https://www.freshports.org/net-mgmt/nvidia_gpu_prometheus_exporter/

**Comment by rohitagarwal003** [comment]
So cool. Thanks for letting me know! :)

Also for reference, this seems to be the commit that added it: https://github.com/freebsd/freebsd-ports/commit/59d35f52ec246afc80dcb2d9b3edbad38a0be818
